add

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -65,11 +65,11 @@ jobs:
         run: |
           sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /www/wwwroot/keysport-api.sitilink.vn && chown -R www:www storage bootstrap/cache && chmod -R 775 storage bootstrap/cache"
 
-      - name: Run php artisan storage:link
-        env:
-          SSHPASS: ${{ secrets.SSH_PASSWORD }}
-        run: |
-          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /www/wwwroot/keysport-api.sitilink.vn && /www/server/php/82/bin/php artisan storage:link || { echo 'SSH command failed'; exit 1; }"
+#      - name: Run php artisan storage:link
+#        env:
+#          SSHPASS: ${{ secrets.SSH_PASSWORD }}
+#        run: |
+#          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /www/wwwroot/keysport-api.sitilink.vn && /www/server/php/82/bin/php artisan storage:link || { echo 'SSH command failed'; exit 1; }"
 
   deploy_frontend:
     runs-on: ubuntu-latest
