adđ

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,22 +50,22 @@ jobs:
         env:
           SSHPASS: ${{ secrets.SSH_PASSWORD }}
         run: |
-          sshpass -e scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} backend.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/www/wwwroot/admin.goldone-restaurant.com
-          sshpass -e scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} vendor.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/www/wwwroot/admin.goldone-restaurant.com
-          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "unzip -o /www/wwwroot/admin.goldone-restaurant.com/backend.zip -d /www/wwwroot/admin.goldone-restaurant.com/ && rm /www/wwwroot/admin.goldone-restaurant.com/backend.zip"
-          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "unzip -o /www/wwwroot/admin.goldone-restaurant.com/vendor.zip -d /www/wwwroot/admin.goldone-restaurant.com/ && rm /www/wwwroot/admin.goldone-restaurant.com/vendor.zip"
+          sshpass -e scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} backend.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/www/wwwroot/keysport-api.sitilink.vn
+          sshpass -e scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} vendor.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/www/wwwroot/keysport-api.sitilink.vn
+          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "unzip -o /www/wwwroot/keysport-api.sitilink.vn/backend.zip -d /www/wwwroot/keysport-api.sitilink.vn/ && rm /www/wwwroot/keysport-api.sitilink.vn/backend.zip"
+          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "unzip -o /www/wwwroot/keysport-api.sitilink.vn/vendor.zip -d /www/wwwroot/keysport-api.sitilink.vn/ && rm /www/wwwroot/keysport-api.sitilink.vn/vendor.zip"
 
       - name: Set permissions for storage and bootstrap/cache
         env:
           SSHPASS: ${{ secrets.SSH_PASSWORD }}
         run: |
-          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /www/wwwroot/admin.goldone-restaurant.com && chown -R www:www storage bootstrap/cache && chmod -R 775 storage bootstrap/cache"
+          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /www/wwwroot/keysport-api.sitilink.vn && chown -R www:www storage bootstrap/cache && chmod -R 775 storage bootstrap/cache"
 
       - name: Run php artisan storage:link
         env:
           SSHPASS: ${{ secrets.SSH_PASSWORD }}
         run: |
-          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /www/wwwroot/admin.goldone-restaurant.com && /www/server/php/82/bin/php artisan storage:link || { echo 'SSH command failed'; exit 1; }"
+          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /www/wwwroot/keysport-api.sitilink.vn && /www/server/php/82/bin/php artisan storage:link || { echo 'SSH command failed'; exit 1; }"
 
   deploy_frontend:
     runs-on: ubuntu-latest
